version: '3.9'

volumes:
  database:

networks:
  ml_network_app:
    name: ml_network_app
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.0.0/24"
          gateway: "172.16.0.1"

services:
  nodejs:
    container_name: ml-controller-api-app
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
      args:
        APP_STAGE: 'prod'
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    volumes:
      - .:/opt/app
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    links:
      - "postgres:db_postgres"
    # network_mode: host
    networks:
      ml_network_app:

  postgres:
    container_name: ml-controller-api-postgres
    build:
      context: .
      dockerfile: ./docker/postgres.Dockerfile
      args:
        APP_STAGE: 'dev'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      ml_network_app:
    #     aliases:
    #       - default_network